version: "3"
services:
  nginx-streamer:
    image: nginx-streamer
    environment:
      - "TITLE=My Stream"
      - "STREAM_NAME=myStream"
      - "SERVER_IP=192.168.83.179"
      - "WORKER_PROCESSES=1"
      - "NGINX_HTTP_CONF=access_log /tmp/hls/access.log;" 
      - "IFRAME=https://google.com" 
      - "GANALYTICS=UA-00000000-0"
      - "BLACKLIST_MESSAGE=<strong>Blacklist Message!</strong>"
        # Blacklisted IPs with be redirected to error page
      - "BLACKLIST_IPS=192.168.120.5 1;192.168.120.6 1;"  
      - "HEADER=<h1>myStream</h1>"
      - "FOOTER=footer message"
    deploy:
      replicas: 2
      resources:
        limits:
          # 10% of CPU all cores
          cpus: "0.1"
          memory: 250M
      restart_policy:
        condition: on-failure
    ports:
      - "1935:1935"
      - "80:8080"
    networks:
      - webnet
networks:
  webnet:
